import { MarketEngine } from '../engine/marketEngine.js';
import { CipherTrainingRoom } from './CipherTrainingRoom.js';
const hash = async value => [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))].map(n=>n.toString(16).padStart(2,'0')).join('');
const button=(label,action)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=async()=>{b.disabled=true;try{await action();}catch(e){b.title=e.message;const status=b.closest('dialog')?.querySelector('[data-status],.training-result');if(status)status.textContent=e.message;}finally{if(!b.dataset.locked)b.disabled=false;}};return b;};
export function installOnlineCompetition(Competition) {
    const originalRender=Competition.prototype.render,originalJoin=Competition.prototype.requestJoin;
    Object.assign(Competition.prototype,{
        async arenaRequest(input) {
            if(!window.stockWarsArena?.request)throw new Error('온라인 대결은 서버에 연결된 데스크톱 앱에서 이용할 수 있습니다. AI 모드는 계속 이용할 수 있습니다.');
            const result=await window.stockWarsArena.request(input);if(result.error)throw Object.assign(new Error(result.error),{retryable:result.retryable});return result;
        },
        open(){this.dialog.showModal();this.render();void this.refreshPublicRooms();this.publicTimer=setInterval(()=>this.refreshPublicRooms(),2000);},
        close(){clearInterval(this.publicTimer);if(this.onlineState?.room)this.arenaRequest({action:'leave',id:this.onlineState.room.id}).catch(()=>{});this.onlineState=null;this.dialog.close();this.onClose?.();},
        render(){
            originalRender.call(this);
            const form=this.dialog.querySelector('[data-create]'),submit=form.onsubmit;
            const label=document.createElement('label');label.textContent='대결 방식';const mode=document.createElement('select');mode.name='mode';
            for(const [value,text] of [['online','온라인 · 친구/다른 플레이어'],['ai','AI · 혼자 플레이']]){const option=document.createElement('option');option.value=value;option.textContent=text;mode.append(option);}label.append(mode);form.prepend(label);
            form.querySelector('small').textContent='0G는 무료 · 대결 전용 가상 배팅 · 실제 계좌에 영향 없음';
            form.onsubmit=async e=>{e.preventDefault();if(mode.value==='ai'){await submit(e);return;}const data=new FormData(form);const target=form.querySelector('button');target.disabled=true;try{const state=await this.arenaRequest({action:'create',room:{name:String(data.get('name')).trim(),minutes:Number(data.get('minutes')),cash:Number(data.get('cash')),stake:Number(data.get('stake')),passwordHash:data.get('access')==='locked'?await hash(String(data.get('password'))):null}});this.onlineState=state;this.renderOnlineRoom(state);await this.refreshPublicRooms();}catch(error){this.dialog.querySelector('[data-status]').textContent=error.message;}finally{target.disabled=false;}};
            this.dialog.querySelector('[data-friends]')?.nextElementSibling?.remove();
            this.dialog.querySelector('[data-friend]').onsubmit=async e=>{e.preventDefault();const name=String(new FormData(e.target).get('name')).trim();try{const found=await window.stockWarsChat.friends('search',undefined,{query:name});if(found.error)throw new Error(found.error);const peer=found.players?.[0];if(!peer)throw new Error('해당 닉네임을 찾을 수 없습니다.');const result=await window.stockWarsChat.friends('request',peer.id,{targetName:peer.name});if(result.error)throw new Error(result.error);this.dialog.querySelector('[data-status]').textContent='친구 요청을 보냈습니다. 수락 후 목록에 표시됩니다.';}catch(error){this.dialog.querySelector('[data-status]').textContent=error.message;}await this.refreshFriends();};
            const finder=this.dialog.querySelector('[data-find]');finder.onsubmit=async e=>{e.preventDefault();const list=this.dialog.querySelector('[data-find-results]');list.replaceChildren();try{const {rooms}=await this.arenaRequest({action:'find',query:String(new FormData(finder).get('query'))});for(const room of rooms)list.append(this.onlineRoomCard(room));this.dialog.querySelector('[data-find-status]').textContent=rooms.length?'검색 결과':'검색 결과가 없습니다.';}catch(error){this.dialog.querySelector('[data-find-status]').textContent=error.message;}};
            if(this.onlineState)this.renderOnlineRoom(this.onlineState);
            void this.refreshFriends();
            this.dialog.querySelector('header').append(button('전적 보기',()=>this.showArenaHistory()));
        },
        async showArenaHistory(){
            const popup=document.createElement('dialog');popup.className='settings-dialog';popup.setAttribute('aria-label','모의투자 전적');const title=document.createElement('h2');title.textContent='모의투자 전적';const list=document.createElement('div');list.style.cssText='max-height:calc(60 * var(--game-vh));overflow:auto';popup.append(title,list,button('닫기',()=>{popup.close();popup.remove();}));this.dialog.append(popup);popup.showModal();
            try{const {records}=await this.arenaRequest({action:'history'});const local=JSON.parse(localStorage.getItem('stockwars.arena.aiHistory')||'[]');for(const r of [...records,...local].sort((a,b)=>b.ended-a.ended)){const card=document.createElement('section');card.style.cssText='border-bottom:1px solid #456075;padding:12px';const mine=r.results.find(p=>p.isOwn),winner=r.results.filter(p=>p.rank===1&&!p.forfeited).map(p=>p.name).join(', ');card.textContent=`${new Date(r.ended).toLocaleString('ko-KR')} · ${r.name}${r.ai?' · AI':''} · 승자 ${winner||'없음'} · 내 순위 ${mine?.rank||'-'}위 · 최종 자산 ${Math.round(mine?.assets||0).toLocaleString()}G · 가상 배당 ${(mine?.payout||0).toLocaleString()}G · 실제 지급 0G`;list.append(card);}if(!list.children.length)list.textContent='아직 완료한 대결이 없습니다.';}catch(e){list.textContent=e.message;}
        },
        returnToArenaLobby(){this.resultDialog?.close();this.resultDialog?.remove();this.resultDialog=null;this.match?.close();this.onlineState=null;this.onlineMatchId=null;this.resultConfirmed=false;this.pendingArenaOrder=null;this.render();void this.refreshPublicRooms();},
        async refreshFriends(){
            const list=this.dialog.querySelector('[data-friends]');if(!list||!window.stockWarsChat?.friends)return;
            try{const state=await window.stockWarsChat.friends('list');if(state.error)throw new Error(state.error);list.replaceChildren();if(!state.friends.length){const p=document.createElement('p');p.textContent='등록된 친구가 없습니다. 친구가 요청을 수락하면 표시됩니다.';list.append(p);}for(const friend of state.friends){const row=document.createElement('div');row.style.cssText='display:flex;align-items:center;gap:12px;padding:14px 0;border-bottom:1px solid #344e68';const name=document.createElement('span');name.textContent=`${friend.online?'🟢 온라인':'⚪ 오프라인'} · ${friend.name}`;name.style.flex='1';row.append(name);const invite=button('초대',async()=>{try{await this.arenaRequest({action:'invite',id:this.onlineState.room.id,targetName:friend.name});this.dialog.querySelector('[data-status]').textContent=`${friend.name}님에게 초대를 보냈습니다.`;}catch(e){this.dialog.querySelector('[data-status]').textContent=e.message;}});invite.disabled=!friend.online||!this.onlineState?.isHost||this.onlineState.phase!=='waiting';invite.title=invite.disabled?'방을 만든 뒤 접속 중인 친구를 초대하세요.':'이 방으로 초대';row.append(invite);list.append(row);}}catch(e){list.textContent=e.message;}
        },
        onlineRoomCard(room){const card=document.createElement('section');card.style.cssText='padding:14px;border:1px solid #456075;border-radius:12px;margin:12px 0';const title=document.createElement('p');title.textContent=`${room.locked?'🔒 ':''}${room.name} · ${room.host} · ${room.count}/8명 · ${room.minutes}분`;card.append(title,button('참가',()=>this.requestJoin(room)));return card;},
        paintPublicRooms(){const list=this.dialog.querySelector('[data-public-rooms]');if(!list)return;list.replaceChildren();this.dialog.querySelector('[data-public-status]').textContent=this.publicError||'온라인 공개방';for(const room of this.publicRooms||[])list.append(this.onlineRoomCard(room));for(const room of this.invites||[]){const card=this.onlineRoomCard(room);card.querySelector('p').textContent=`📨 ${room.host}님의 초대 · ${room.name}`;list.prepend(card);}for(const room of this.serverOwnRooms||[]){if(room.id===this.onlineState?.room.id)continue;const card=this.onlineRoomCard(room);card.querySelector('p').textContent=`내 참가 방 · ${room.name}`;list.prepend(card);}},
        async refreshPublicRooms(){if(this.publicLoading)return;this.publicLoading=true;try{const result=await this.arenaRequest({action:'list'});this.publicRooms=result.rooms;this.invites=result.invitations;this.serverOwnRooms=result.ownRooms;this.publicError=null;if(this.onlineState){const state=await this.arenaRequest({action:'state',id:this.onlineState.room.id});this.onlineState=state;if(state.phase==='running'||state.phase==='finished')this.updateOnlineMatch(state);else this.renderOnlineRoom(state);}}catch(error){this.publicError=error.message;if(this.onlineState?.phase==='finished'&&error.message.includes('방이 종료'))this.returnToArenaLobby();}finally{this.publicLoading=false;if(this.dialog.open){this.paintPublicRooms();await this.refreshFriends();}}},
        async requestJoin(room){if(!room.online){return originalJoin.call(this,room);}let passwordHash;if(room.locked&&!this.invites?.some(r=>r.id===room.id)&&!this.serverOwnRooms?.some(r=>r.id===room.id)){const popup=document.createElement('dialog');popup.className='settings-dialog';const label=document.createElement('p');label.textContent=`${room.name} · 비밀번호`;const input=document.createElement('input');input.type='password';input.maxLength=32;const status=document.createElement('p');popup.append(label,input,status,button('참가',async()=>{try{const state=await this.arenaRequest({action:'join',id:room.id,passwordHash:await hash(input.value)});popup.close();popup.remove();this.enterOnline(state);}catch(e){status.textContent=e.message;}}),button('닫기',()=>{popup.close();popup.remove();}));this.dialog.append(popup);popup.showModal();return;}try{this.enterOnline(await this.arenaRequest({action:'join',id:room.id,passwordHash}));}catch(e){this.dialog.querySelector('[data-status]').textContent=e.message;}},
        enterOnline(state){this.onlineState=state;if(state.phase==='waiting')this.renderOnlineRoom(state);else this.updateOnlineMatch(state);void this.refreshFriends();},
        renderOnlineRoom(state){const main=this.dialog.querySelector('.training-workspace>main');if(!main)return;main.replaceChildren();const title=document.createElement('h3');title.textContent=`${state.room.name} · 온라인 대기실`;const details=document.createElement('p');details.textContent=`${state.room.minutes}분 · 시작 자금 ${state.room.cash.toLocaleString()}G · 방 코드 ${state.room.id}`;main.append(title,details);for(const member of state.members){const p=document.createElement('p');p.textContent=`${member.online?'🟢':'⚪'} ${member.name}${member.isHost?' · 방장':''}${member.isOwn?' · 나':''} · ${member.ready?'준비 완료':'준비 중'}`;main.append(p);}const mine=state.members.find(m=>m.isOwn);main.append(button(mine?.ready?'준비 취소':'준비',async()=>{this.onlineState=await this.arenaRequest({action:'ready',id:state.room.id,ready:!mine?.ready});this.renderOnlineRoom(this.onlineState);}));if(state.isHost)main.append(button('온라인 대결 시작',async()=>{try{this.enterOnline(await this.arenaRequest({action:'start',id:state.room.id}));}catch(e){this.dialog.querySelector('[data-status]').textContent=e.message;}}));main.append(button('방 나가기',async()=>{await this.arenaRequest({action:'leave',id:state.room.id});this.onlineState=null;this.render();}));},
        updateOnlineMatch(state){
            if(this.resultConfirmed&&state.allConfirmed){this.returnToArenaLobby();return;}
            if(this.onlineMatchId!==state.room.id){this.match?.dialog.remove();const engine=new MarketEngine();engine.stopEngine();this.onlineEngine=engine;this.match=new CipherTrainingRoom(this.container,engine);this.onlineMatchId=state.room.id;this.resultShown=false;this.match.dialog.querySelector('h2').textContent=`${state.room.name} · 온라인`;this.onlineStatus=document.createElement('p');this.onlineStatus.style.cssText='padding:14px;color:#f5d583;background:#142c3e';this.match.dialog.querySelector('header').after(this.onlineStatus);this.onlineNews=this.createNewsPanel(this.match);this.seenOnlineNews=new Set();this.match.order=side=>this.onlineOrder(side);this.match.onClose=()=>{void this.arenaRequest({action:'leave',id:state.room.id}).catch(()=>{});this.onlineState=null;this.onlineMatchId=null;this.onlineEngine.stopEngine();this.render();};this.match.open();}
            const engine=this.onlineEngine;engine.cash=state.market.cash;engine.initialCash=state.room.cash;engine.stocks=new Map(state.market.stocks.map(s=>[s.id,s]));engine.priceHistory=new Map(Object.entries(state.histories));engine.portfolio=new Map(state.market.portfolio.map(p=>[`${p.id}_LONG_1`,{id:p.id,qty:p.qty,avgPrice:p.avgPrice,collateral:p.collateral,leverage:1,isShort:false}]));engine.news=state.market.news;engine.notify();
            const ordered=[...state.members].sort((a,b)=>b.assets-a.assets);this.onlineStatus.textContent=`남은 시간 ${Math.floor(state.remaining/60)}:${String(state.remaining%60).padStart(2,'0')} · ${ordered.map((p,i)=>`${i+1}위 ${p.name} ${Math.round(p.assets).toLocaleString()}G`).join(' / ')}`;
            for(const news of [...state.market.news].reverse()){if(this.seenOnlineNews.has(news.id))continue;this.seenOnlineNews.add(news.id);this.addNewsCard(this.match,this.onlineNews,{stock:engine.stocks.get(news.stockId),title:news.title,detail:news.content,time:new Date(news.time).toLocaleTimeString('ko-KR')});}
            for(const side of ['buy','sell'])this.match.dialog.querySelector(`[data-${side}]`).disabled=state.phase!=='running'||!!this.pendingArenaOrder;
            if(state.phase==='finished'&&!this.resultShown){this.resultShown=true;this.resultConfirmed=false;const results=document.createElement('dialog');this.resultDialog=results;results.className='settings-dialog';results.setAttribute('aria-label','온라인 대결 결과');const title=document.createElement('h2');const winners=(state.results||[]).filter(r=>r.rank===1&&!r.forfeited);title.textContent=winners.length?`승자: ${winners.map(r=>r.name).join(', ')}`:'대결 종료 · 승자 없음';results.append(title);for(const r of state.results||[]){const p=document.createElement('p');p.textContent=`${r.rank}위 ${r.name}${r.isOwn?' · 나':''} · 최종 자산 ${Math.round(r.assets).toLocaleString()}G · 가상 배당 ${(r.payout||0).toLocaleString()}G · 배팅 손익 ${(r.netPayout||0).toLocaleString()}G${r.forfeited?' · 포기':''}`;results.append(p);}const note=document.createElement('p');note.textContent='모의투자 전용 가상 배당입니다. 실제 계좌 지급액은 0G입니다.';const progress=document.createElement('p');progress.dataset.confirmations='';results.append(note,progress,button('확인',async()=>{const acknowledged=await this.arenaRequest({action:'ack',id:state.room.id});this.resultConfirmed=true;results.querySelector('button').disabled=true;results.querySelector('button').dataset.locked='true';results.querySelector('button').textContent='다른 참가자 확인 대기';this.updateOnlineMatch(acknowledged);}));results.addEventListener('cancel',e=>e.preventDefault());this.match.dialog.append(results);results.showModal();}
            if(this.resultDialog?.open)this.resultDialog.querySelector('[data-confirmations]').textContent=`확인 ${state.confirmed||0}/${state.participants||state.members.length}명 · 모두 확인하면 로비로 돌아갑니다.`;
            if(this.pendingArenaOrder&&!this.orderLoading)void this.onlineOrder(this.pendingArenaOrder.side);
        },
        async onlineOrder(side){if(this.orderLoading||this.onlineState?.phase!=='running')return;this.orderLoading=true;const match=this.match;this.pendingArenaOrder ||= {action:'trade',id:this.onlineState.room.id,side,stockId:match.selected,quantity:Number(match.dialog.querySelector('[type=number]').value),requestId:crypto.randomUUID()};try{const state=await this.arenaRequest(this.pendingArenaOrder);this.pendingArenaOrder=null;this.onlineState=state;this.updateOnlineMatch(state);match.dialog.querySelector('.training-result').textContent=`${state.trade.side==='buy'?'매수':'매도'} ${state.trade.quantity}주 · 체결가 ${state.trade.price.toLocaleString()}G`;}catch(e){if(!e.retryable)this.pendingArenaOrder=null;match.dialog.querySelector('.training-result').textContent=e.message;}finally{this.orderLoading=false;}}
    });
}
